import { Marko_One } from "next/font/google";
import {Providers} from "../provider";
import './globals.css'

const markoOne = Marko_One({ weight : '400', subsets : ['latin'] });

export const metadata = {
  title: "Tasklify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={markoOne.className}><Providers>{children}</Providers></body>
    </html>
  );
}
